Traceback (most recent call last):
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
pd.read_excel('data/test.xls')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
File [0;32m~/.conda/envs/myenv/lib/python3.11/site-packages/pandas/compat/_optional.py:142[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    141[0m [38;5;28;01mtry[39;00m:
[0;32m--> 142[0m     module [38;5;241m=[39m importlib[38;5;241m.[39mimport_module(name)
[1;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:

File [0;32m~/.conda/envs/myenv/lib/python3.11/importlib/__init__.py:126[0m, in [0;36mimport_module[0;34m(name, package)[0m
[1;32m    125[0m         level [38;5;241m+[39m[38;5;241m=[39m [38;5;241m1[39m
[0;32m--> 126[0m [38;5;28;01mreturn[39;00m _bootstrap[38;5;241m.[39m_gcd_import(name[level:], package, level)

File [0;32m<frozen importlib._bootstrap>:1204[0m, in [0;36m_gcd_import[0;34m(name, package, level)[0m

File [0;32m<frozen importlib._bootstrap>:1176[0m, in [0;36m_find_and_load[0;34m(name, import_)[0m

File [0;32m<frozen importlib._bootstrap>:1140[0m, in [0;36m_find_and_load_unlocked[0;34m(name, import_)[0m

[0;31mModuleNotFoundError[0m: No module named 'xlrd'

During handling of the above exception, another exception occurred:

[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[22], line 1[0m
[0;32m----> 1[0m pd[38;5;241m.[39mread_excel([38;5;124m'[39m[38;5;124mdata/test.xls[39m[38;5;124m'[39m)

File [0;32m~/.conda/envs/myenv/lib/python3.11/site-packages/pandas/io/excel/_base.py:478[0m, in [0;36mread_excel[0;34m(io, sheet_name, header, names, index_col, usecols, dtype, engine, converters, true_values, false_values, skiprows, nrows, na_values, keep_default_na, na_filter, verbose, parse_dates, date_parser, date_format, thousands, decimal, comment, skipfooter, storage_options, dtype_backend)[0m
[1;32m    476[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28misinstance[39m(io, ExcelFile):
[1;32m    477[0m     should_close [38;5;241m=[39m [38;5;28;01mTrue[39;00m
[0;32m--> 478[0m     io [38;5;241m=[39m ExcelFile(io, storage_options[38;5;241m=[39mstorage_options, engine[38;5;241m=[39mengine)
[1;32m    479[0m [38;5;28;01melif[39;00m engine [38;5;129;01mand[39;00m engine [38;5;241m!=[39m io[38;5;241m.[39mengine:
[1;32m    480[0m     [38;5;28;01mraise[39;00m [38;5;167;01mValueError[39;00m(
[1;32m    481[0m         [38;5;124m"[39m[38;5;124mEngine should not be specified when passing [39m[38;5;124m"[39m
[1;32m    482[0m         [38;5;124m"[39m[38;5;124man ExcelFile - ExcelFile already has the engine set[39m[38;5;124m"[39m
[1;32m    483[0m     )

File [0;32m~/.conda/envs/myenv/lib/python3.11/site-packages/pandas/io/excel/_base.py:1513[0m, in [0;36mExcelFile.__init__[0;34m(self, path_or_buffer, engine, storage_options)[0m
[1;32m   1510[0m [38;5;28mself[39m[38;5;241m.[39mengine [38;5;241m=[39m engine
[1;32m   1511[0m [38;5;28mself[39m[38;5;241m.[39mstorage_options [38;5;241m=[39m storage_options
[0;32m-> 1513[0m [38;5;28mself[39m[38;5;241m.[39m_reader [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39m_engines[engine]([38;5;28mself[39m[38;5;241m.[39m_io, storage_options[38;5;241m=[39mstorage_options)

File [0;32m~/.conda/envs/myenv/lib/python3.11/site-packages/pandas/io/excel/_xlrd.py:34[0m, in [0;36mXlrdReader.__init__[0;34m(self, filepath_or_buffer, storage_options)[0m
[1;32m     24[0m [38;5;250m[39m[38;5;124;03m"""[39;00m
[1;32m     25[0m [38;5;124;03mReader using xlrd engine.[39;00m
[1;32m     26[0m 
[0;32m   (...)[0m
[1;32m     31[0m [38;5;124;03m{storage_options}[39;00m
[1;32m     32[0m [38;5;124;03m"""[39;00m
[1;32m     33[0m err_msg [38;5;241m=[39m [38;5;124m"[39m[38;5;124mInstall xlrd >= 2.0.1 for xls Excel support[39m[38;5;124m"[39m
[0;32m---> 34[0m import_optional_dependency([38;5;124m"[39m[38;5;124mxlrd[39m[38;5;124m"[39m, extra[38;5;241m=[39merr_msg)
[1;32m     35[0m [38;5;28msuper[39m()[38;5;241m.[39m[38;5;21m__init__[39m(filepath_or_buffer, storage_options[38;5;241m=[39mstorage_options)

File [0;32m~/.conda/envs/myenv/lib/python3.11/site-packages/pandas/compat/_optional.py:145[0m, in [0;36mimport_optional_dependency[0;34m(name, extra, errors, min_version)[0m
[1;32m    143[0m [38;5;28;01mexcept[39;00m [38;5;167;01mImportError[39;00m:
[1;32m    144[0m     [38;5;28;01mif[39;00m errors [38;5;241m==[39m [38;5;124m"[39m[38;5;124mraise[39m[38;5;124m"[39m:
[0;32m--> 145[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(msg)
[1;32m    146[0m     [38;5;28;01mreturn[39;00m [38;5;28;01mNone[39;00m
[1;32m    148[0m [38;5;66;03m# Handle submodules: if we have submodule, grab parent module from sys.modules[39;00m

[0;31mImportError[0m: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.
ImportError: Missing optional dependency 'xlrd'. Install xlrd >= 2.0.1 for xls Excel support Use pip or conda to install xlrd.

