Traceback (most recent call last):
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/spellizzeri/.conda/envs/myenv/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
DNA = SeqIO.parse('data/DNA_sequence_drago.fasta', 'fasta')
rat_seq = [x.seq for x in DNA]

SeqUtils.gc_fraction(*rat_seq)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 4[0m
[1;32m      1[0m DNA [38;5;241m=[39m SeqIO[38;5;241m.[39mparse([38;5;124m'[39m[38;5;124mdata/DNA_sequence_drago.fasta[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mfasta[39m[38;5;124m'[39m)
[1;32m      2[0m rat_seq [38;5;241m=[39m [x[38;5;241m.[39mseq [38;5;28;01mfor[39;00m x [38;5;129;01min[39;00m DNA]
[0;32m----> 4[0m SeqUtils[38;5;241m.[39mgc_fraction([38;5;241m*[39mrat_seq)

[0;31mAttributeError[0m: module 'Bio.SeqUtils' has no attribute 'gc_fraction'
AttributeError: module 'Bio.SeqUtils' has no attribute 'gc_fraction'

